/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import EstructurasDatos.ListaSimple;
import EstructurasDatos.Vertice;
import static Interfaz.AgregarEstacionesLinea.verticesNuevos;
import static Interfaz.CargarRed.FuncionesApp;
import static Interfaz.CargarRed.redTransporte;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author mateusnaddaf
 */
public class AgregarConexion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarConexion
     */
    
     DefaultComboBoxModel modeloParadas = new  DefaultComboBoxModel();
      DefaultComboBoxModel modeloParadasLinea = new  DefaultComboBoxModel();
     
     
    public AgregarConexion() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        modeloParadas.removeAllElements();
        modeloParadasLinea.removeAllElements();
        
        this.agregarParadasRed();
        this.agregarParadasLinea();
    }
    
    private void agregarParadasRed(){
        ListaSimple nombres = FuncionesApp.listaParadas(redTransporte, 2);
        for (int i = 0; i < nombres.getSize(); i++) {
            modeloParadas.addElement(nombres.getValor(i));
        }
    }
    
    private void agregarParadasLinea(){
        ListaSimple nombres = FuncionesApp.nombresVertices(verticesNuevos);
        for (int i = 0; i < nombres.getSize(); i++) {
            modeloParadasLinea.addElement(nombres.getValor(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paradaRed = new javax.swing.JComboBox<>();
        agregarConexionAction = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        paradasLineaNueva = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Conexion de Linea con Red");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Estacion de la Linea Nueva:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Estacion de la Red:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        paradaRed.setModel(modeloParadas);
        paradaRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paradaRedActionPerformed(evt);
            }
        });
        getContentPane().add(paradaRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 20));

        agregarConexionAction.setText("Añadir conexion");
        agregarConexionAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarConexionActionActionPerformed(evt);
            }
        });
        getContentPane().add(agregarConexionAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        paradasLineaNueva.setModel(modeloParadasLinea);
        paradasLineaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paradasLineaNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(paradasLineaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paradaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paradaRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paradaRedActionPerformed

    private void agregarConexionActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarConexionActionActionPerformed
        String nombreParadaLineaNueva = (String) paradasLineaNueva.getSelectedItem();
        String nombreParadaRed = (String) paradaRed.getSelectedItem();
        
        FuncionesApp.agregarVertices(redTransporte, verticesNuevos);
        
            Vertice verticeInicio = redTransporte.buscarVerticePorNombre(nombreParadaRed);
            Vertice verticeFinal = redTransporte.buscarVerticePorNombre(nombreParadaLineaNueva);
            
            redTransporte.conectarVertices(verticeInicio, verticeFinal);
            
            JOptionPane.showMessageDialog(null, "Conexion de la Linea Nueva con el Grafo realizada con exito.");
            verticesNuevos.destruir();
            
            Menu menu = new Menu();
            this.dispose();
    }//GEN-LAST:event_agregarConexionActionActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        AgregarEstacionesLinea agregarEstaciones = new AgregarEstacionesLinea();
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void paradasLineaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paradasLineaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paradasLineaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarConexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JButton agregarConexionAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> paradaRed;
    private javax.swing.JComboBox<String> paradasLineaNueva;
    // End of variables declaration//GEN-END:variables
}
