/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Funciones.RedEstacionesVisualizador;
import static Interfaz.CargarRed.FuncionesApp;
import static Interfaz.CargarRed.redTransporte;
import javax.swing.JOptionPane;

/**
 *
 * @author mateusnaddaf
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BusquedaBFS = new javax.swing.JButton();
        BusquedaDFS = new javax.swing.JButton();
        ColocarSucursal = new javax.swing.JButton();
        EliminarSucursal = new javax.swing.JButton();
        EstablecerT = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        AgregarLinea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        BusquedaBFS.setBackground(new java.awt.Color(204, 204, 0));
        BusquedaBFS.setText("Busqueda BFS");
        BusquedaBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaBFSActionPerformed(evt);
            }
        });
        jPanel1.add(BusquedaBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 40));

        BusquedaDFS.setBackground(new java.awt.Color(204, 204, 0));
        BusquedaDFS.setText("Busqueda DFS");
        BusquedaDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaDFSActionPerformed(evt);
            }
        });
        jPanel1.add(BusquedaDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, 40));

        ColocarSucursal.setBackground(new java.awt.Color(204, 204, 0));
        ColocarSucursal.setText("Colocar Sucursal");
        ColocarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(ColocarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 40));

        EliminarSucursal.setBackground(new java.awt.Color(204, 204, 0));
        EliminarSucursal.setText("Eliminar Sucursal");
        EliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, 40));

        EstablecerT.setBackground(new java.awt.Color(204, 204, 0));
        EstablecerT.setText("Establecer T");
        EstablecerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstablecerTActionPerformed(evt);
            }
        });
        jPanel1.add(EstablecerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 130, 40));

        jButton6.setBackground(new java.awt.Color(204, 204, 0));
        jButton6.setText("Mostrar Grafo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, 30));

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        volver.setBackground(new java.awt.Color(204, 204, 0));
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        AgregarLinea.setBackground(new java.awt.Color(204, 204, 0));
        AgregarLinea.setText("Agregar Linea");
        AgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLineaActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstablecerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstablecerTActionPerformed
        EstablecerT v1 = new EstablecerT();
        this.dispose();
    }//GEN-LAST:event_EstablecerTActionPerformed

    private void EliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSucursalActionPerformed
        if(FuncionesApp.haySucursales(redTransporte)){
            EliminarSucursal v1 = new EliminarSucursal();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Debe existir al menos una sucursal en la red para poder ingresar a esta ventana.");
        }
    }//GEN-LAST:event_EliminarSucursalActionPerformed

    private void BusquedaDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaDFSActionPerformed
        if (FuncionesApp.haySucursales(redTransporte)) {
            BusquedaDFS busquedaDFS = new BusquedaDFS();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe existir al menos una sucursal en la red para poder ingresar a esta ventana.");
        }
    }//GEN-LAST:event_BusquedaDFSActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        redTransporte.destruir();
        CargarRed cargarRed = new CargarRed();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void ColocarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarSucursalActionPerformed
        ColocarSucursal v1 = new ColocarSucursal();
        this.dispose();
    }//GEN-LAST:event_ColocarSucursalActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLineaActionPerformed
        AgregarLinea v1 = new AgregarLinea();
        this.dispose();
    }//GEN-LAST:event_AgregarLineaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.setProperty("org.graphstream.ui", "swing");
        RedEstacionesVisualizador visualizador = new RedEstacionesVisualizador(redTransporte);
        visualizador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BusquedaBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaBFSActionPerformed
        if (FuncionesApp.haySucursales(redTransporte)) {
            BusquedaBFS busquedaBFS = new BusquedaBFS();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe existir al menos una sucursal en la red para poder ingresar a esta ventana.");
        }
    }//GEN-LAST:event_BusquedaBFSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLinea;
    private javax.swing.JButton BusquedaBFS;
    private javax.swing.JButton BusquedaDFS;
    private javax.swing.JButton ColocarSucursal;
    private javax.swing.JButton EliminarSucursal;
    private javax.swing.JButton EstablecerT;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
